### ISSUE TITLE
Конфликт с функцией Assist

### ISSUE THREAD

**Issue by dext0r** [dext0r/ha-yandex-station-intents#21]
При вызове функции Assist в логах появляется:
```
2023-03-09 08:19:03.928 ERROR (MainThread) [homeassistant.helpers.integration_platform] Error processing platform yandex_station_intents.intent
Traceback (most recent call last):
  File ".venv-2023/lib/python3.10/site-packages/homeassistant/helpers/integration_platform.py", line 51, in _async_process_single_integration_platform_component
    await integration_platform.process_platform(hass, component_name, platform)
  File ".venv-2023/lib/python3.10/site-packages/homeassistant/components/intent/__init__.py", line 203, in _async_process_intent
    await platform.async_setup_intents(hass)
AttributeError: module 'custom_components.yandex_station_intents.intent' has no attribute 'async_setup_intents'
```

**Comment by Dremalka** [comment]
Такая же ошибка.

Home Assistant 2023.3.5
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.1 - latest

Logger: homeassistant.helpers.integration_platform
Source: components/intent/__init__.py:203
First occurred: 11:22:42 (1 occurrences)
Last logged: 11:22:42

Error processing platform yandex_station_intents.intent
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 51, in _async_process_single_integration_platform_component
    await integration_platform.process_platform(hass, component_name, platform)
  File "/usr/src/homeassistant/homeassistant/components/intent/__init__.py", line 203, in _async_process_intent
    await platform.async_setup_intents(hass)
AttributeError: module 'custom_components.yandex_station_intents.intent' has no attribute 'async_setup_intents'
