### ISSUE TITLE
Интеграция не стартует при старте ХА

### ISSUE THREAD

**Issue by to4ko** [dext0r/ha-yandex-station-intents#46]
Интеграция версии 0.6.0 не стартует при старте ХА (supervised 2024.7.4), но если нажать релоад - все запускается корректно.

в логе ошибка 

```
Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: August 5, 2024 at 21:54:18 (1 occurrences)
Last logged: August 5, 2024 at 21:54:18

Error setting up entry xxxxxxxxxx for yandex_station_intents
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station_intents/__init__.py", line 183, in async_setup_entry
    session = YandexSession(hass, entry)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station_intents/yandex_session.py", line 94, in __init__
    cast(CookieJar, self._session.cookie_jar)._cookies = pickle.loads(raw)
                                                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/cookies.py", line 312, in __setitem__
    raise CookieError("Invalid attribute %r" % (K,))
http.cookies.CookieError: Invalid attribute 'partitioned
```

**Comment by to4ko** [comment]
как фича, было бы полезно добавить сущность статуса. и если бы она становилась офф или недоступна, то прям автоматизацией дергать релоад интеграции

**Comment by meteonet** [comment]
Точно такая же проблема при перезапуске HA 2024.8.3 Docker. Если после перезапуска HA перезапустить интеграцию - все продолжает работать.

```
2024-09-05 10:44:27.010 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ********* for yandex_station_intents

Traceback (most recent call last):

File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup

result = await component.async_setup_entry(hass, self)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/yandex_station_intents/__init__.py", line 183, in async_setup_entry

session = YandexSession(hass, entry)

^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/yandex_station_intents/yandex_session.py", line 94, in __init__

cast(CookieJar, self._session.cookie_jar)._cookies = pickle.loads(raw)

^^^^^^^^^^^^^^^^^

File "/usr/local/lib/python3.12/http/cookies.py", line 312, in __setitem__

raise CookieError("Invalid attribute %r" % (K,))

http.cookies.CookieError: Invalid attribute 'partitioned'
```

**Comment by KarasN** [comment]
Та же проблема и уже давно

**Comment by dext0r** [comment]
Исправлено в 0.6.1
