### ISSUE TITLE
Ошибка при вызове yandex_station_intents.clear_scenarios

### ISSUE THREAD

**Issue by dummylabs** [dext0r/ha-yandex-station-intents#9]
Приветствую, спасибо за компонент! 
Пробую добавить компонент через Device&Services->Add двумя способами: через импорт credentials Yandex Station и через копирование токена из конфига. В обоих случаях интеграция сообщает об успехе, но в списке интеграций показывается вот это (см. скрин). При этом в логе нет никаких ошибок, даже при включении `yandex_station_intents: debug` в настройках логера. Yandex Station с этим токеном работает.

<img width="284" alt="Settings_–_Home_Assistant" src="https://user-images.githubusercontent.com/4209521/172858954-4bc7a19b-05cc-4fea-89d3-af076c258a20.png">

Вижу, что в списке сервисов есть сервисы YS.intents, пробую очистить список интентов. Получаю две ошибки в логе (ключ на всякий случай изменил):

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/yandex_station_intents/__init__.py:91
Integration: Yandex.Station Intents ([documentation](https://github.com/dext0r/ha-yandex-station-intents), [issues](https://github.com/dext0r/ha-yandex-station-intents/issues))
First occurred: 4:19:00 PM (1 occurrences)
Last logged: 4:19:00 PM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'f222dc050d3199785c9260cc7ad60908'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/yandex_station_intents/__init__.py", line 91, in _clear_scenarios
    quasar = hass.data[DOMAIN][entry.entry_id][DATA_QUASAR]
KeyError: 'f222dc050d3199785c9260cc7ad60908'
```

и 

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/yandex_station_intents/__init__.py:91
Integration: Yandex.Station Intents ([documentation](https://github.com/dext0r/ha-yandex-station-intents), [issues](https://github.com/dext0r/ha-yandex-station-intents/issues))
First occurred: 4:19:00 PM (1 occurrences)
Last logged: 4:19:00 PM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'f222dc050d3199785c9260cc7ad60908'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/yandex_station_intents/__init__.py", line 91, in _clear_scenarios
    quasar = hass.data[DOMAIN][entry.entry_id][DATA_QUASAR]
KeyError: 'f222dc050d3199785c9260cc7ad60908'
```

**Comment by dummylabs** [comment]
Попробовал третий способ через passport.yandex.com - результат такой же.
Кстати, в описании метода вместо passport.yandex.com написано yandex.passport.com, хотя ссылка верная.

**Comment by dummylabs** [comment]
Действительно, в.raw логе ошибка есть. Такое ощущение, что оно пытается показать мне капчу:
```
2022-06-09 17:43:18 WARNING (MainThread) [homeassistant.config_entries] Config entry 's***a' for yandex_station_intents integration not ready yet: b'<!DOCTYPE html>\n<html><head><title>403</title><meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<style>body{font-family:Arial,sans-serif;margin:0;padding:0;color:#000;background-color:#fff}.header{height:48px}.header__logo{display:inline-block;overflow:hidden;width:130px;height:48px;white-space:nowrap;text-indent:100%;background-repeat:no-repeat;background-position:center bottom}.header__code{font-size:32px;display:inline-block;overflow:hidden;width:76px;height:48px;text-align:center;color:#fff;background-color:#999}.header__logo_lang_ru{background-image:url(//yastatic.net/islands/_/5vJOTgN-leXxtlxIFPiM-vfC24o.png)}.header__logo_lang_en{background-image:url(//yastatic.net/islands/_/fGdVzvAAq7J8px5LpiysN6M_sy8.png)}.content{font-size:15px;line-height:20px;margin:20px 0 30px;padding-left:25px}.content__h1{font-size:21px;font-weight:400}.footer{line-height:30px;height:30px;padding:0 25px;border-top:1px solid #eee}.footer__copyright{font-size:13px}.link{color:#44b}.link:hover{color:#e00}</style>\n<!--[if gt IE 8]><!--><link rel="stylesheet" href="captcha.min.css"/><!--<![endif]--><!--[if lte IE 8]><link rel="stylesheet" href="captcha.ie.min.css"/><![endif]-->\n</head><body><div class=\'header\'>\n    <a class="header__logo header__logo_lang_ru" href="https://www.yandex.ru/">\xd0\xaf\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xba\xd1\x81</a>\n<div class=\'header__code\'>403</div></div><div class=\'content\'>\n    <h1 class="content__h1">\xd0\x94\xd0\xbe\xd1\x81\xd1\x82\xd1\x83\xd0\xbf \xd0\xba&nbsp;\xd0\xbd\xd0\xb0\xd1\x88\xd0\xb5\xd0\xbc\xd1\x83 \xd1\x81\xd0\xb5\xd1\x80\xd0\xb2\xd0\xb8\xd1\x81\xd1\x83 \xd0\xb2\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe \xd0\xb7\xd0\xb0\xd0\xbf\xd1\x80\xd0\xb5\xd1\x89\xd1\x91\xd0\xbd!</h1><p>\xd0\x92\xd0\xbe\xd0\xb7\xd0\xbc\xd0\xbe\xd0\xb6\xd0\xbd\xd0\xbe, \xd0\xb2\xd0\xb0\xd1\x88 \xd0\xba\xd0\xbe\xd0\xbc\xd0\xbf\xd1\x8c\xd1\x8e\xd1\x82\xd0\xb5\xd1\x80 \xd0\xb7\xd0\xb0\xd1\x80\xd0\xb0\xd0\xb6\xd1\x91\xd0\xbd \xd0\xb2\xd1\x80\xd0\xb5\xd0\xb4\xd0\xbe\xd0\xbd\xd0\xbe\xd1\x81\xd0\xbd\xd0\xbe\xd0\xb9 \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb3\xd1\x80\xd0\xb0\xd0\xbc\xd0\xbc\xd0\xbe\xd0\xb9, \xd0\xba\xd0\xbe\xd1\x82\xd0\xbe\xd1\x80\xd0\xb0\xd1\x8f \xd0\xb0\xd0\xb2\xd1\x82\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x82\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8 \xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd1\x89\xd0\xb0\xd0\xb5\xd1\x82\xd1\x81\xd1\x8f \xd0\xba&nbsp;\xd0\xaf\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xba\xd1\x81\xd1\x83.<br>\xd0\xa0\xd0\xb5\xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xb4\xd1\x83\xd0\xb5\xd0\xbc \xd0\xb2\xd0\xb0\xd0\xbc \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd0\xb8\xd1\x82\xd1\x8c \xd0\xba\xd0\xbe\xd0\xbc\xd0\xbf\xd1\x8c\xd1\x8e\xd1\x82\xd0\xb5\xd1\x80 \xd0\xbd\xd0\xb0&nbsp;\xd0\xb2\xd0\xb8\xd1\x80\xd1\x83\xd1\x81\xd1\x8b \xd0\xb8\xd0\xbb\xd0\xb8 \xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd1\x82\xd0\xb8\xd1\x82\xd1\x8c\xd1\x81\xd1\x8f \xd0\xba&nbsp;\xd0\xb0\xd0\xb4\xd0\xbc\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb0\xd1\x82\xd0\xbe\xd1\x80\xd1\x83 \xd0\xb2\xd0\xb0\xd1\x88\xd0\xb5\xd0\xb9 \xd1\x81\xd0\xb5\xd1\x82\xd0\xb8.</p><p>\xd0\x95\xd1\x81\xd0\xbb\xd0\xb8 \xd1\x83&nbsp;\xd0\xb2\xd0\xb0\xd1\x81 \xd0\xb2\xd0\xbe\xd0\xb7\xd0\xbd\xd0\xb8\xd0\xba\xd0\xbb\xd0\xb8 \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb1\xd0\xbb\xd0\xb5\xd0\xbc\xd1\x8b \xd0\xb8\xd0\xbb\xd0\xb8 \xd0\xb2\xd1\x8b&nbsp;\xd1\x85\xd0\xbe\xd1\x82\xd0\xb8\xd1\x82\xd0\xb5 \xd0\xb7\xd0\xb0\xd0\xb4\xd0\xb0\xd1\x82\xd1\x8c \xd0\xb2\xd0\xbe\xd0\xbf\xd1\x80\xd0\xbe\xd1\x81 \xd0\xbd\xd0\xb0\xd1\x88\xd0\xb5\xd0\xb9 \xd1\x81\xd0\xbb\xd1\x83\xd0\xb6\xd0\xb1\xd0\xb5 \xd0\xbf\xd0\xbe\xd0\xb4\xd0\xb4\xd0\xb5\xd1\x80\xd0\xb6\xd0\xba\xd0\xb8, \xd0\xbf\xd0\xbe\xd0\xb6\xd0\xb0\xd0\xbb\xd1\x83\xd0\xb9\xd1\x81\xd1\x82\xd0\xb0, \xd0\xb2\xd0\xbe\xd1\x81\xd0\xbf\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb7\xd1\x83\xd0\xb9\xd1\x82\xd0\xb5\xd1\x81\xd1\x8c <a class="link" href="https://yandex.ru/support/smart-captcha/?unique_key=74c24b32-7770ee8b-7504e06d-e8e2ba09" onclick="ym(15897442, \'reachGoal\', \'support_complain\', { \'req_id\': \'1654785798260386-5541700312044906280-sas3-0890-7ac-sas-l7-balancer-8080-BAL\' }); return true;">\xd1\x84\xd0\xbe\xd1\x80\xd0\xbc\xd0\xbe\xd0\xb9 \xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb9 \xd1\x81\xd0\xb2\xd1\x8f\xd0\xb7\xd0\xb8</a>.</p>\n    <p>74c24b32-7770ee8b-7504e06d-e8e2ba09</p>\n</div><div class=\'footer\'><span class=\'footer__copyright\'>\xc2\xa9&nbsp;\xd0\xaf\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xba\xd1\x81</span></div><!-- Yandex.Metrika counter --><script type="text/javascript">(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)}; m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)}) (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(15897442, "init", { clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, ut:"noindex", params:{ "req_id": "1654785798260386-5541700312044906280-sas3-0890-7ac-sas-l7-balancer-8080-BAL", "unique_key": "74c24b32-7770ee8b-7504e06d-e8e2ba09" } });</script><noscript><div><img src="https://mc.yandex.ru/watch/15897442?ut=noindex" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter --></body></html>'; Retrying in background
```

**Comment by dext0r** [comment]
Попробуйте:
1. Поставить компонент из мастера
2. Удалить интеграцию и добавить снова

**Comment by dummylabs** [comment]
Спасибо, всё заработало!
